/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AppDisponibilidadeRouteImport } from './routes/_app/disponibilidade'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAlterarSenhaRouteImport } from './routes/_app/alterar-senha'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAdminUsuariosRouteImport } from './routes/_app/admin.usuarios'
import { Route as AppAdminPerformanceRouteImport } from './routes/_app/admin.performance'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDisponibilidadeRoute = AppDisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlterarSenhaRoute = AppAlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPerformanceRoute = AppAdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agenda': typeof AppAgendaRoute
  '/alterar-senha': typeof AppAlterarSenhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/disponibilidade': typeof AppDisponibilidadeRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/admin/performance': typeof AppAdminPerformanceRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agenda': typeof AppAgendaRoute
  '/alterar-senha': typeof AppAlterarSenhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/disponibilidade': typeof AppDisponibilidadeRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/admin/performance': typeof AppAdminPerformanceRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/alterar-senha': typeof AppAlterarSenhaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disponibilidade': typeof AppDisponibilidadeRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/_app/admin/performance': typeof AppAdminPerformanceRoute
  '/_app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/admin'
    | '/agenda'
    | '/alterar-senha'
    | '/dashboard'
    | '/disponibilidade'
    | '/agendar/$slug'
    | '/admin/performance'
    | '/admin/usuarios'
    | '/api/public/calendar/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/admin'
    | '/agenda'
    | '/alterar-senha'
    | '/dashboard'
    | '/disponibilidade'
    | '/agendar/$slug'
    | '/admin/performance'
    | '/admin/usuarios'
    | '/api/public/calendar/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/$slug'
    | '/login'
    | '/_app/admin'
    | '/_app/agenda'
    | '/_app/alterar-senha'
    | '/_app/dashboard'
    | '/_app/disponibilidade'
    | '/agendar/$slug'
    | '/_app/admin/performance'
    | '/_app/admin/usuarios'
    | '/api/public/calendar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  LoginRoute: typeof LoginRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/disponibilidade': {
      id: '/_app/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof AppDisponibilidadeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/alterar-senha': {
      id: '/_app/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AppAlterarSenhaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/usuarios': {
      id: '/_app/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/performance': {
      id: '/_app/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AppAdminPerformanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminPerformanceRoute: typeof AppAdminPerformanceRoute
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminPerformanceRoute: AppAdminPerformanceRoute,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgendaRoute: typeof AppAgendaRoute
  AppAlterarSenhaRoute: typeof AppAlterarSenhaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisponibilidadeRoute: typeof AppDisponibilidadeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgendaRoute: AppAgendaRoute,
  AppAlterarSenhaRoute: AppAlterarSenhaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisponibilidadeRoute: AppDisponibilidadeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  LoginRoute: LoginRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
